name: xenotes
description: "notes ,camera, and editor application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-180.3.beta <4.0.0'

dependencies:
  camerawesome: ^2.0.1
  external_path: ^1.0.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  local_shared: ^1.0.5
  modal_bottom_sheet: ^3.0.0
  path_provider: ^2.1.3
  pro_image_editor: ^4.3.0
  responsive_builder: ^0.7.1
  share_plus: ^9.0.0
  sqflite: ^2.3.3+1
  status_bar_control: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/default.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/default.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"

flutter:
  assets:
  - assets/
  uses-material-design: true
